In [1]:
import pandas as pd

path = "../23Q_counts_data ex.xlsx"
df = pd.read_excel(path)

In [2]:
df = df[df['23Q'] > 1]
df.reset_index(drop=True, inplace=True)
df

                Geneid  23Q
0      ENSG00000223972    7
1      ENSG00000227232   38
2      ENSG00000279928   12
3      ENSG00000279457   79
4      ENSG00000228463    5
...                ...  ...
25092  ENSG00000278817   68
25093  ENSG00000277196   30
25094  ENSG00000277856    5
25095  ENSG00000275063    8
25096  ENSG00000271254  117

[25097 rows x 2 columns]

In [3]:
from readcount import ReadCountProcessor

processor = ReadCountProcessor(df, gene_limit=100)
normalized_df = processor.normalize_read_counts(max_workers=100)
normalized_df

Fetching gene counts from Ensembl...
Successfully fetched data for ENSG00000223972
Successfully fetched data for ENSG00000227232
Successfully fetched data for ENSG00000224969
Successfully fetched data for ENSG00000235098
Successfully fetched data for ENSG00000078808
Successfully fetched data for ENSG00000231050
Successfully fetched data for ENSG00000225880
Successfully fetched data for ENSG00000225630
Successfully fetched data for ENSG00000233542
Successfully fetched data for ENSG00000188976
Successfully fetched data for ENSG00000228463
Successfully fetched data for ENSG00000248527
Successfully fetched data for ENSG00000107404
Successfully fetched data for ENSG00000272161
Successfully fetched data for ENSG00000237973
Successfully fetched data for ENSG00000176022
Successfully fetched data for ENSG00000221978
Successfully fetched data for ENSG00000230021
Successfully fetched data for ENSG00000184163
Successfully fetched data for ENSG00000279928
Successfully fetched data for ENSG00000215790
Successfully fetched data for ENSG00000215014
Failed to fetch data for ENSG00000131584Failed to fetch data for ENSG00000236679
Failed to fetch data for ENSG00000160072
Failed to fetch data for ENSG00000175756
Failed to fetch data for ENSG00000230699
Failed to fetch data for ENSG00000272438
Failed to fetch data for ENSG00000223764
Failed to fetch data for ENSG00000187634
Failed to fetch data for ENSG00000116151

Failed to fetch data for ENSG00000279457
Failed to fetch data for ENSG00000142609
Failed to fetch data for ENSG00000127054
Failed to fetch data for ENSG00000169972
Failed to fetch data for ENSG00000224870
Failed to fetch data for ENSG00000008128
Failed to fetch data for ENSG00000230092
Failed to fetch data for ENSG00000269737
Failed to fetch data for ENSG00000182873
Failed to fetch data for ENSG00000067606
Failed to fetch data for ENSG00000078369
Failed to fetch data for ENSG00000157916
Failed to fetch data for ENSG00000242485
Failed to fetch data for ENSG00000187961
Failed to fetch data for ENSG00000241180
Failed to fetch data for ENSG00000157881
Failed to fetch data for ENSG00000162572
Failed to fetch data for ENSG00000187730
Failed to fetch data for ENSG00000272512
Failed to fetch data for ENSG00000162585
Failed to fetch data for ENSG00000169962
Failed to fetch data for ENSG00000131591
Failed to fetch data for ENSG00000157933
Failed to fetch data for ENSG00000240409
Failed to fetch data for ENSG00000272106
Failed to fetch data for ENSG00000268575
Failed to fetch data for ENSG00000149527
Failed to fetch data for ENSG00000272420
Failed to fetch data for ENSG00000187583
Failed to fetch data for ENSG00000227775
Failed to fetch data for ENSG00000272455
Failed to fetch data for ENSG00000188290
Failed to fetch data for ENSG00000179403
Failed to fetch data for ENSG00000225972
Failed to fetch data for ENSG00000189339
Failed to fetch data for ENSG00000217801
Failed to fetch data for ENSG00000228794
Failed to fetch data for ENSG00000162576
Failed to fetch data for ENSG00000157873
Failed to fetch data for ENSG00000160075
Failed to fetch data for ENSG00000177757
Failed to fetch data for ENSG00000198744
Failed to fetch data for ENSG00000187642
Failed to fetch data for ENSG00000157911
Failed to fetch data for ENSG00000215915
Failed to fetch data for ENSG00000225931
Failed to fetch data for ENSG00000228327
Failed to fetch data for ENSG00000231702
Failed to fetch data for ENSG00000248333
Failed to fetch data for ENSG00000197530
Failed to fetch data for ENSG00000225285
Failed to fetch data for ENSG00000197785
Failed to fetch data for ENSG00000169885
Failed to fetch data for ENSG00000269896
Failed to fetch data for ENSG00000230415
Failed to fetch data for ENSG00000187608
Failed to fetch data for ENSG00000272004
Failed to fetch data for ENSG00000008130
Failed to fetch data for ENSG00000271806
Failed to fetch data for ENSG00000237491
Failed to fetch data for ENSG00000160087
Failed to fetch data for ENSG00000240731
Failed to fetch data for ENSG00000228594
Failed to fetch data for ENSG00000229344
Failed to fetch data for ENSG00000237094
Failed to fetch data for ENSG00000224051
Failed to fetch data for ENSG00000272449
Failed to fetch data for ENSG00000178821
Failed to fetch data for ENSG00000188157
Finished fetching all gene counts.

                Geneid  23Q  Normalized_Read_Counts
0      ENSG00000223972    7                     7.0
1      ENSG00000227232   38                    38.0
2      ENSG00000279928   12                    12.0
3      ENSG00000279457   79                    79.0
4      ENSG00000228463    5                     5.0
...                ...  ...                     ...
25092  ENSG00000278817   68                    68.0
25093  ENSG00000277196   30                    30.0
25094  ENSG00000277856    5                     5.0
25095  ENSG00000275063    8                     8.0
25096  ENSG00000271254  117                   117.0

[25097 rows x 3 columns]

In [4]:
from geneconverter import convert_dataframe_parallel

df_with_ncbi = convert_dataframe_parallel(normalized_df, row_limit=200, max_workers=100)
df_with_ncbi = df_with_ncbi[pd.to_numeric(df_with_ncbi['NCBI_ID'], errors='coerce').notnull()]
df_with_ncbi

Converting ENSG00000223972 to NCBI ID...
Converting ENSG00000227232 to NCBI ID...
Converting ENSG00000279928 to NCBI ID...
Converting ENSG00000279457 to NCBI ID...
Converting ENSG00000228463 to NCBI ID...
Converting ENSG00000236679 to NCBI ID...
Converting ENSG00000237094 to NCBI ID...
Converting ENSG00000230021 to NCBI ID...
Converting ENSG00000225972 to NCBI ID...
Converting ENSG00000225630 to NCBI ID...
Converting ENSG00000237973 to NCBI ID...
Converting ENSG00000229344 to NCBI ID...
Converting ENSG00000240409 to NCBI ID...
Converting ENSG00000248527 to NCBI ID...
Converting ENSG00000198744 to NCBI ID...
Converting ENSG00000228327 to NCBI ID...
Converting ENSG00000237491 to NCBI ID...
Converting ENSG00000230092 to NCBI ID...
Converting ENSG00000177757 to NCBI ID...
Converting ENSG00000228794 to NCBI ID...
Converting ENSG00000225880 to NCBI ID...
Converting ENSG00000272438 to NCBI ID...
Converting ENSG00000230699 to NCBI ID...
Converting ENSG00000241180 to NCBI ID...
Converting ENSG00000223764 to NCBI ID...
Converting ENSG00000187634 to NCBI ID...
Converting ENSG00000188976 to NCBI ID...
Converting ENSG00000187961 to NCBI ID...
Converting ENSG00000187583 to NCBI ID...
Converting ENSG00000187642 to NCBI ID...
Converting ENSG00000272512 to NCBI ID...
Converting ENSG00000188290 to NCBI ID...
Converting ENSG00000187608 to NCBI ID...
Converting ENSG00000231702 to NCBI ID...
Converting ENSG00000224969 to NCBI ID...
Converting ENSG00000188157 to NCBI ID...
Converting ENSG00000217801 to NCBI ID...
Converting ENSG00000131591 to NCBI ID...
Converting ENSG00000078808 to NCBI ID...
Converting ENSG00000176022 to NCBI ID...
Converting ENSG00000184163 to NCBI ID...
Converting ENSG00000160087 to NCBI ID...
Converting ENSG00000230415 to NCBI ID...
Converting ENSG00000162572 to NCBI ID...
Converting ENSG00000131584 to NCBI ID...
Converting ENSG00000169972 to NCBI ID...
Converting ENSG00000127054 to NCBI ID...
Converting ENSG00000240731 to NCBI ID...
Converting ENSG00000224051 to NCBI ID...
Converting ENSG00000169962 to NCBI ID...
Converting ENSG00000107404 to NCBI ID...
Converting ENSG00000162576 to NCBI ID...
Converting ENSG00000175756 to NCBI ID...
Converting ENSG00000221978 to NCBI ID...
Converting ENSG00000224870 to NCBI ID...
Converting ENSG00000242485 to NCBI ID...
Converting ENSG00000272455 to NCBI ID...
Converting ENSG00000235098 to NCBI ID...
Converting ENSG00000225285 to NCBI ID...
Converting ENSG00000179403 to NCBI ID...
Converting ENSG00000215915 to NCBI ID...
Converting ENSG00000160072 to NCBI ID...
Converting ENSG00000197785 to NCBI ID...
Converting ENSG00000160075 to NCBI ID...
Converting ENSG00000215014 to NCBI ID...
Converting ENSG00000228594 to NCBI ID...
Converting ENSG00000272106 to NCBI ID...
Converting ENSG00000197530 to NCBI ID...
Converting ENSG00000248333 to NCBI ID...
Converting ENSG00000272004 to NCBI ID...
Converting ENSG00000189339 to NCBI ID...
Converting ENSG00000269737 to NCBI ID...
Converting ENSG00000008128 to NCBI ID...
Converting ENSG00000268575 to NCBI ID...
Converting ENSG00000227775 to NCBI ID...
Converting ENSG00000215790 to NCBI ID...
Converting ENSG00000008130 to NCBI ID...
Converting ENSG00000078369 to NCBI ID...
Converting ENSG00000231050 to NCBI ID...
Converting ENSG00000169885 to NCBI ID...
Converting ENSG00000178821 to NCBI ID...
Converting ENSG00000142609 to NCBI ID...
Converting ENSG00000233542 to NCBI ID...
Converting ENSG00000187730 to NCBI ID...
Converting ENSG00000067606 to NCBI ID...
Converting ENSG00000271806 to NCBI ID...
Converting ENSG00000182873 to NCBI ID...
Converting ENSG00000162585 to NCBI ID...
Converting ENSG00000157933 to NCBI ID...
Converting ENSG00000116151 to NCBI ID...
Converting ENSG00000272161 to NCBI ID...
Converting ENSG00000269896 to NCBI ID...
Converting ENSG00000272420 to NCBI ID...
Converting ENSG00000157916 to NCBI ID...
Converting ENSG00000157911 to NCBI ID...
Converting ENSG00000149527 to NCBI ID...
Converting ENSG00000157881 to NCBI ID...
Converting ENSG00000272449 to NCBI ID...
Converting ENSG00000157873 to NCBI ID...
Converting ENSG00000225931 to NCBI ID...

15:51:06 - WARNING - No UniProt entry was found for ID ENSG00000279928.
15:51:06 - WARNING - No UniProt entry was found for ID ENSG00000228463.
15:51:06 - WARNING - No UniProt entry was found for ID ENSG00000236679.

Converting ENSG00000157870 to NCBI ID...

15:51:07 - WARNING - No UniProt entry was found for ID ENSG00000227232.

Error converting ENSG00000187961: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000142606 to NCBI ID...

15:51:07 - WARNING - No UniProt entry was found for ID ENSG00000248527.
15:51:08 - WARNING - No UniProt entry was found for ID ENSG00000240409.

Error converting ENSG00000177757: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000215912 to NCBI ID...
Error converting ENSG00000230021: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000279839 to NCBI ID...
Error converting ENSG00000230092: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000130762 to NCBI ID...
Error converting ENSG00000279457: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000272088 to NCBI ID...

15:51:08 - WARNING - No UniProt entry was found for ID ENSG00000237973.
15:51:08 - WARNING - ID 'ENSG00000241180' not found. Please double-check spelling/arguments and try again.

Converting ENSG00000162591 to NCBI ID...
Error converting ENSG00000241180: 'NoneType' object has no attribute 'ncbi_gene_id'
Converting ENSG00000238260 to NCBI ID...
Error converting ENSG00000272512: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000158109 to NCBI ID...
Error converting ENSG00000188290: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000116213 to NCBI ID...
Error converting ENSG00000225880: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Error converting ENSG00000078808: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000078900 to NCBI ID...
Converting ENSG00000227589 to NCBI ID...
Error converting ENSG00000131591: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000235131 to NCBI ID...
Error converting ENSG00000225630: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000227372 to NCBI ID...

15:51:08 - WARNING - No UniProt entry was found for ID ENSG00000223764.
15:51:09 - WARNING - No UniProt entry was found for ID ENSG00000237094.

Error converting ENSG00000176022: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000162592 to NCBI ID...
Error converting ENSG00000225972: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000235169 to NCBI ID...
Error converting ENSG00000198744: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000130764 to NCBI ID...
Error converting ENSG00000188157: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000266075 to NCBI ID...
Error converting ENSG00000187608: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000272153 to NCBI ID...
Error converting ENSG00000237491: http://rest.ensembl.org/ returned error status code 429. Please double-check arguments and try again.

Converting ENSG00000116198 to NCBI ID...
Converting ENSG00000169598 to NCBI ID...

15:51:09 - WARNING - No UniProt entry was found for ID ENSG00000272438.

Converting ENSG00000198912 to NCBI ID...

15:51:09 - WARNING - No UniProt entry was found for ID ENSG00000228327.

Converting ENSG00000236423 to NCBI ID...
Converting ENSG00000233304 to NCBI ID...
Error converting ENSG00000160087: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000232596 to NCBI ID...
Error converting ENSG00000169962: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000196581 to NCBI ID...
Converting ENSG00000131697 to NCBI ID...

15:51:10 - WARNING - No UniProt entry was found for ID ENSG00000229344.
15:51:10 - WARNING - No UniProt entry was found for ID ENSG00000223972.
15:51:10 - WARNING - No UniProt entry was found for ID ENSG00000231702.

Converting ENSG00000069424 to NCBI ID...
Converting ENSG00000116254 to NCBI ID...

15:51:10 - WARNING - No UniProt entry was found for ID ENSG00000217801.
15:51:10 - WARNING - No UniProt entry was found for ID ENSG00000240731.

Converting ENSG00000116251 to NCBI ID...
Converting ENSG00000226944 to NCBI ID...
Converting ENSG00000158286 to NCBI ID...

15:51:11 - WARNING - No UniProt entry was found for ID ENSG00000228794.

Converting ENSG00000116237 to NCBI ID...

15:51:11 - WARNING - No UniProt entry was found for ID ENSG00000230415.

Converting ENSG00000225077 to NCBI ID...
Converting ENSG00000158292 to NCBI ID...
Converting ENSG00000097021 to NCBI ID...

15:51:12 - WARNING - No UniProt entry was found for ID ENSG00000215014.
15:51:12 - WARNING - No UniProt entry was found for ID ENSG00000272004.
15:51:12 - WARNING - No UniProt entry was found for ID ENSG00000272106.

Converting ENSG00000069812 to NCBI ID...
Error converting ENSG00000189339: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000215788 to NCBI ID...
Converting ENSG00000171680 to NCBI ID...
Converting ENSG00000162408 to NCBI ID...
Converting ENSG00000229519 to NCBI ID...

15:51:13 - WARNING - No UniProt entry was found for ID ENSG00000269737.
15:51:13 - WARNING - No UniProt entry was found for ID ENSG00000215790.
15:51:13 - WARNING - No UniProt entry was found for ID ENSG00000268575.
15:51:13 - WARNING - No UniProt entry was found for ID ENSG00000224870.
15:51:13 - WARNING - No UniProt entry was found for ID ENSG00000227775.
15:51:14 - WARNING - No UniProt entry was found for ID ENSG00000231050.

Error converting ENSG00000142609: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000173662 to NCBI ID...
Error converting ENSG00000157933: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000204859 to NCBI ID...
Converting ENSG00000162413 to NCBI ID...
Converting ENSG00000116273 to NCBI ID...
Converting ENSG00000041988 to NCBI ID...
Converting ENSG00000007923 to NCBI ID...

15:51:15 - WARNING - No UniProt entry was found for ID ENSG00000271806.
15:51:15 - WARNING - No UniProt entry was found for ID ENSG00000233542.

Converting ENSG00000237436 to NCBI ID...
Converting ENSG00000171735 to NCBI ID...
Converting ENSG00000270171 to NCBI ID...
Converting ENSG00000270035 to NCBI ID...
Converting ENSG00000269978 to NCBI ID...

15:51:15 - WARNING - ID 'ENSG00000230699' not found. Please double-check spelling/arguments and try again.
15:51:15 - WARNING - No UniProt entry was found for ID ENSG00000182873.

Error converting ENSG00000230699: 'NoneType' object has no attribute 'ncbi_gene_id'
Converting ENSG00000049245 to NCBI ID...
Error converting ENSG00000157881: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000269925 to NCBI ID...
Converting ENSG00000049246 to NCBI ID...
Converting ENSG00000236266 to NCBI ID...
Converting ENSG00000049247 to NCBI ID...
Converting ENSG00000049249 to NCBI ID...

15:51:15 - WARNING - No UniProt entry was found for ID ENSG00000269896.
15:51:15 - WARNING - No UniProt entry was found for ID ENSG00000272420.
15:51:16 - WARNING - No UniProt entry was found for ID ENSG00000272161.
15:51:16 - WARNING - No UniProt entry was found for ID ENSG00000225931.
15:51:16 - WARNING - No UniProt entry was found for ID ENSG00000272449.

Error converting ENSG00000162591: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000116288 to NCBI ID...
Converting ENSG00000116285 to NCBI ID...
Converting ENSG00000238290 to NCBI ID...
Converting ENSG00000233645 to NCBI ID...
Converting ENSG00000162426 to NCBI ID...
Converting ENSG00000142599 to NCBI ID...
Converting ENSG00000229716 to NCBI ID...

15:51:16 - WARNING - No UniProt entry was found for ID ENSG00000272088.
15:51:16 - WARNING - No UniProt entry was found for ID ENSG00000279839.
15:51:17 - WARNING - No UniProt entry was found for ID ENSG00000224969.
15:51:17 - WARNING - No UniProt entry was found for ID ENSG00000238260.

Converting ENSG00000074800 to NCBI ID...

15:51:17 - WARNING - No UniProt entry was found for ID ENSG00000227589.

Converting ENSG00000236269 to NCBI ID...
Converting ENSG00000230679 to NCBI ID...
Converting ENSG00000238249 to NCBI ID...

15:51:18 - WARNING - No UniProt entry was found for ID ENSG00000235131.
15:51:18 - WARNING - No UniProt entry was found for ID ENSG00000272153.
15:51:18 - WARNING - No UniProt entry was found for ID ENSG00000227372.

Converting ENSG00000232663 to NCBI ID...
Converting ENSG00000197241 to NCBI ID...
Converting ENSG00000142583 to NCBI ID...

15:51:18 - WARNING - No UniProt entry was found for ID ENSG00000266075.

Converting ENSG00000180758 to NCBI ID...
Error converting ENSG00000116251: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000228526 to NCBI ID...
Converting ENSG00000234546 to NCBI ID...
Converting ENSG00000049239 to NCBI ID...Converting ENSG00000171621 to NCBI ID...
Converting ENSG00000235263 to NCBI ID...

Converting ENSG00000171612 to NCBI ID...
Converting ENSG00000231181 to NCBI ID...
Converting ENSG00000188807 to NCBI ID...
Converting ENSG00000171608 to NCBI ID...
Converting ENSG00000231789 to NCBI ID...

15:51:19 - WARNING - No UniProt entry was found for ID ENSG00000232596.
15:51:20 - WARNING - No UniProt entry was found for ID ENSG00000226944.

Error converting ENSG00000171680: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000171603 to NCBI ID...
Converting ENSG00000178585 to NCBI ID...
Converting ENSG00000162441 to NCBI ID...
Converting ENSG00000228150 to NCBI ID...
Converting ENSG00000173614 to NCBI ID...

15:51:20 - WARNING - No UniProt entry was found for ID ENSG00000233304.

Error converting ENSG00000041988: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000202415 to NCBI ID...
Converting ENSG00000162444 to NCBI ID...
Error converting ENSG00000116273: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

Converting ENSG00000130939 to NCBI ID...
Converting ENSG00000201746 to NCBI ID...

15:51:21 - WARNING - No UniProt entry was found for ID ENSG00000225077.

Converting ENSG00000054523 to NCBI ID...
Converting ENSG00000199562 to NCBI ID...

15:51:21 - WARNING - No UniProt entry was found for ID ENSG00000236423.
15:51:21 - WARNING - No UniProt entry was found for ID ENSG00000229519.

Converting ENSG00000142657 to NCBI ID...
Converting ENSG00000251503 to NCBI ID...
Converting ENSG00000175279 to NCBI ID...
Converting ENSG00000241563 to NCBI ID...
Converting ENSG00000160049 to NCBI ID...
Converting ENSG00000142655 to NCBI ID...

15:51:22 - WARNING - No UniProt entry was found for ID ENSG00000270035.
15:51:22 - WARNING - No UniProt entry was found for ID ENSG00000270171.
15:51:22 - WARNING - No UniProt entry was found for ID ENSG00000237436.
15:51:22 - WARNING - ID 'ENSG00000236269' not found. Please double-check spelling/arguments and try again.
15:51:22 - WARNING - No UniProt entry was found for ID ENSG00000236266.
15:51:22 - WARNING - No UniProt entry was found for ID ENSG00000269925.

Error converting ENSG00000236269: 'NoneType' object has no attribute 'ncbi_gene_id'

15:51:23 - WARNING - No UniProt entry was found for ID ENSG00000269978.

Error converting ENSG00000197241: http://rest.ensembl.org/ returned error status code 502. Please double-check arguments and try again.

15:51:23 - WARNING - No UniProt entry was found for ID ENSG00000233645.
15:51:23 - WARNING - No UniProt entry was found for ID ENSG00000229716.
15:51:23 - WARNING - No UniProt entry was found for ID ENSG00000238249.
15:51:24 - WARNING - No UniProt entry was found for ID ENSG00000230679.
15:51:24 - WARNING - No UniProt entry was found for ID ENSG00000231181.
15:51:25 - WARNING - No UniProt entry was found for ID ENSG00000235263.
15:51:27 - WARNING - No UniProt entry was found for ID ENSG00000228150.
15:51:27 - WARNING - No UniProt entry was found for ID ENSG00000228526.
15:51:27 - WARNING - No UniProt entry was found for ID ENSG00000202415.
15:51:27 - WARNING - No UniProt entry was found for ID ENSG00000238290.
15:51:27 - WARNING - No UniProt entry was found for ID ENSG00000232663.
15:51:27 - WARNING - No UniProt entry was found for ID ENSG00000234546.
15:51:28 - WARNING - No UniProt entry was found for ID ENSG00000201746.
15:51:29 - WARNING - No reviewed UniProt results were found for ID ENSG00000251503. Returning all unreviewed results.
15:51:30 - WARNING - No UniProt entry was found for ID ENSG00000231789.

Error converting ENSG00000221978: HTTPConnectionPool(host='rest.ensembl.org', port=80): Read timed out. (read timeout=None)
Error converting ENSG00000242485: HTTPConnectionPool(host='rest.ensembl.org', port=80): Read timed out. (read timeout=None)

15:51:32 - ERROR - The NCBI server request for Ensembl ID 'ENSG00000231702' returned the following error:
HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=None)
15:51:32 - ERROR - The NCBI server request for Ensembl ID 'ENSG00000224051' returned the following error:
HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=None)
15:51:32 - ERROR - The NCBI server request for Ensembl ID 'ENSG00000217801' returned the following error:
HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=None)
15:51:32 - ERROR - The NCBI server request for Ensembl ID 'ENSG00000169972' returned the following error:
HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=None)
15:51:32 - ERROR - The NCBI server request for Ensembl ID 'ENSG00000240731' returned the following error:
HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=None)
15:51:32 - ERROR - The NCBI server request for Ensembl ID 'ENSG00000162572' returned the following error:
HTTPSConnectionPool(host='www.ncbi.nlm.nih.gov', port=443): Read timed out. (read timeout=None)
15:51:32 - WARNING - No UniProt entry was found for ID ENSG00000199562.

Error converting ENSG00000272455: HTTPConnectionPool(host='rest.ensembl.org', port=80): Read timed out. (read timeout=None)
Error converting ENSG00000225285: HTTPConnectionPool(host='rest.ensembl.org', port=80): Read timed out. (read timeout=None)
Error converting ENSG00000235098: HTTPConnectionPool(host='rest.ensembl.org', port=80): Read timed out. (read timeout=None)
Error converting ENSG00000179403: HTTPConnectionPool(host='rest.ensembl.org', port=80): Read timed out. (read timeout=None)

15:51:34 - WARNING - UniProt server request for ID 'ENSG00000175756' returned the following error:
HTTPSConnectionPool(host='rest.uniprot.org', port=443): Read timed out. (read timeout=None)
15:51:35 - WARNING - UniProt server request for ID 'ENSG00000107404' returned the following error:
HTTPSConnectionPool(host='rest.uniprot.org', port=443): Read timed out. (read timeout=None)

              Geneid   23Q  Normalized_Read_Counts    NCBI_ID
4    ENSG00000228463     5                     5.0     728481
5    ENSG00000236679     4                     4.0     728517
10   ENSG00000237973  4175                  4175.0  107075141
11   ENSG00000229344  1326                  1326.0  107075310
12   ENSG00000240409     8                     8.0  106480795
..               ...   ...                     ...        ...
195  ENSG00000251503    33                    33.0  100526739
196  ENSG00000175279   157                   157.0     378708
197  ENSG00000241563     2                     2.0       1325
198  ENSG00000160049  1518                  1518.0       1676
199  ENSG00000142655    78                    78.0       5195

[109 rows x 4 columns]

In [5]:
df_with_ncbi_sorted = df_with_ncbi.sort_values(by='Normalized_Read_Counts', ascending=False)
df_with_ncbi_sorted = df_with_ncbi_sorted.iloc[:20]
df_with_ncbi_sorted

              Geneid    23Q  Normalized_Read_Counts    NCBI_ID
165  ENSG00000074800  15997                 15997.0       2023
13   ENSG00000248527   9800                  9800.0  106480796
158  ENSG00000116288   6997                  6997.0      11315
10   ENSG00000237973   4175                  4175.0  107075141
77   ENSG00000078369   3662                  3662.0       2782
135  ENSG00000097021   3113                  3113.0      11332
194  ENSG00000142657   2685                  2685.0       5226
26   ENSG00000188976   2030                  2030.0      26155
148  ENSG00000171735   1901                  1901.0      23261
152  ENSG00000049245   1788                  1788.0       9341
198  ENSG00000160049   1518                  1518.0       1676
11   ENSG00000229344   1326                  1326.0  107075310
46   ENSG00000127054   1248                  1248.0      54973
192  ENSG00000054523   1184                  1184.0      23095
109  ENSG00000116213   1053                  1053.0      49856
63   ENSG00000160075   1042                  1042.0      29101
183  ENSG00000171603    857                   857.0      22883
185  ENSG00000162441    659                   659.0      84328
190  ENSG00000130939    631                   631.0      10277
93   ENSG00000157916    622                   622.0      11079

In [6]:
from geneprocessor import GeneDataProcessor

df_with_ncbi_sorted = GeneDataProcessor.sort_by_read_counts(df_with_ncbi)
df_with_gene_columns = GeneDataProcessor.add_gene_columns(df_with_ncbi_sorted)
df_final = GeneDataProcessor.enrich_gene_data(df_with_gene_columns)

[DEBUG] Fetching data from API for NCBI ID: 2023
[DEBUG] Fetching data from API for NCBI ID: 106480796
[DEBUG] Fetching data from API for NCBI ID: 11315
[DEBUG] Fetching data from API for NCBI ID: 107075141
[DEBUG] Fetching data from API for NCBI ID: 2782
[DEBUG] Fetching data from API for NCBI ID: 11332
[ERROR] Request failed: 429 Client Error: Too Many Requests for url: https://api.ncbi.nlm.nih.gov/datasets/v2/gene/id/11332
[DEBUG] Fetching data from API for NCBI ID: 5226
[ERROR] Request failed: 429 Client Error: Too Many Requests for url: https://api.ncbi.nlm.nih.gov/datasets/v2/gene/id/5226
[DEBUG] Fetching data from API for NCBI ID: 26155
[DEBUG] Fetching data from API for NCBI ID: 23261
[DEBUG] Fetching data from API for NCBI ID: 9341
[DEBUG] Fetching data from API for NCBI ID: 1676
[DEBUG] Fetching data from API for NCBI ID: 107075310
[DEBUG] Fetching data from API for NCBI ID: 54973
[ERROR] Request failed: 429 Client Error: Too Many Requests for url: https://api.ncbi.nlm.nih.gov/datasets/v2/gene/id/54973
[DEBUG] Fetching data from API for NCBI ID: 23095
[ERROR] Request failed: 429 Client Error: Too Many Requests for url: https://api.ncbi.nlm.nih.gov/datasets/v2/gene/id/23095
[DEBUG] Fetching data from API for NCBI ID: 49856
[DEBUG] Fetching data from API for NCBI ID: 29101
[DEBUG] Fetching data from API for NCBI ID: 22883
[DEBUG] Fetching data from API for NCBI ID: 84328
[DEBUG] Fetching data from API for NCBI ID: 10277
[ERROR] Request failed: 429 Client Error: Too Many Requests for url: https://api.ncbi.nlm.nih.gov/datasets/v2/gene/id/10277
[DEBUG] Fetching data from API for NCBI ID: 11079

In [7]:
df_final

,Geneid,23Q,Normalized_Read_Counts,NCBI_ID,gene_id,symbol,description,tax_id,taxname,common_name,...,synonyms,replaced_gene_id,annotations,transcript_count,protein_count,transcript_type_counts,gene_groups,summary,gene_ontology,locus_tag
165,ENSG00000074800,15997,15997.0,2023,2023,ENO1,enolase 1,9606,Homo sapiens,human,...,"[NNE, PPH, MPB1, ENO1L1, ENO1-IT1, HEL-S-17]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",3,3,"[{'type': 'PROTEIN_CODING', 'count': 3}]","[{'id': '2023', 'method': 'NCBI Ortholog'}]",[{'description': 'This gene encodes alpha-enol...,{'molecular_functions': [{'name': 'DNA-binding...,
13,ENSG00000248527,9800,9800.0,106480796,106480796,MTATP6P1,MT-ATP6 pseudogene 1,9606,Homo sapiens,human,...,[],,"[{'assembly_accession': 'GCF_000001405.40', 'a...",0,0,[],[],[],{},
158,ENSG00000116288,6997,6997.0,11315,11315,PARK7,Parkinsonism associated deglycase,9606,Homo sapiens,human,...,"[DJ1, DJ-1, GATD2, HEL-S-67p]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",4,4,"[{'type': 'PROTEIN_CODING', 'count': 2}, {'typ...","[{'id': '11315', 'method': 'NCBI Ortholog'}]",[{'description': 'The product of this gene bel...,{'molecular_functions': [{'name': 'DNA-binding...,
10,ENSG00000237973,4175,4175.0,107075141,107075141,MTCO1P12,MT-CO1 pseudogene 12,9606,Homo sapiens,human,...,[],,"[{'assembly_accession': 'GCF_000001405.40', 'a...",0,0,[],[],[],{},
77,ENSG00000078369,3662,3662.0,2782,2782,GNB1,G protein subunit beta 1,9606,Homo sapiens,human,...,"[MDS, HG2A, MRD42]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",66,66,"[{'type': 'PROTEIN_CODING', 'count': 3}, {'typ...","[{'id': '2782', 'method': 'NCBI Ortholog'}]",[{'description': 'Heterotrimeric guanine nucle...,{'molecular_functions': [{'name': 'GTPase acti...,
135,ENSG00000097021,3113,3113.0,11332,,,,,,,...,[],,[],0,0,[],[],[],{},
194,ENSG00000142657,2685,2685.0,5226,,,,,,,...,[],,[],0,0,[],[],[],{},
26,ENSG00000188976,2030,2030.0,26155,26155,NOC2L,NOC2 like nucleolar associated transcriptional...,9606,Homo sapiens,human,...,"[NIR, NET7, NET15, PPP1R112]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",1,1,"[{'type': 'PROTEIN_CODING', 'count': 1}]","[{'id': '26155', 'method': 'NCBI Ortholog'}]",[{'description': 'Histone modification by hist...,{'molecular_functions': [{'name': 'DNA-binding...,
148,ENSG00000171735,1901,1901.0,23261,23261,CAMTA1,calmodulin binding transcription activator 1,9606,Homo sapiens,human,...,"[CECBA, CANPMR]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",84,75,"[{'type': 'PROTEIN_CODING', 'count': 24}, {'ty...","[{'id': '23261', 'method': 'NCBI Ortholog'}]",[{'description': 'The protein encoded by this ...,{'molecular_functions': [{'name': 'double-stra...,
152,ENSG00000049245,1788,1788.0,9341,9341,VAMP3,vesicle associated membrane protein 3,9606,Homo sapiens,human,...,[CEB],,"[{'assembly_accession': 'GCF_000001405.40', 'a...",1,1,"[{'type': 'PROTEIN_CODING', 'count': 1}]","[{'id': '9341', 'method': 'NCBI Ortholog'}]","[{'description': 'Synaptobrevins/VAMPs, syntax...",{'molecular_functions': [{'name': 'SNAP recept...,
198,ENSG00000160049,1518,1518.0,1676,1676,DFFA,DNA fragmentation factor subunit alpha,9606,Homo sapiens,human,...,"[DFF1, ICAD, DFF-45]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",2,2,"[{'type': 'PROTEIN_CODING', 'count': 2}]","[{'id': '1676', 'method': 'NCBI Ortholog'}]",[{'description': 'Apoptosis is a cell death pr...,{'molecular_functions': [{'name': 'deoxyribonu...,
11,ENSG00000229344,1326,1326.0,107075310,107075310,MTCO2P12,MT-CO2 pseudogene 12,9606,Homo sapiens,human,...,"[COII, COX2, COXII, MTCO2, MT-CO2]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",0,0,[],[],[{'description': 'Contributes to cytochrome-c ...,{'molecular_functions': [{'name': 'copper ion ...,
46,ENSG00000127054,1248,1248.0,54973,,,,,,,...,[],,[],0,0,[],[],[],{},
192,ENSG00000054523,1184,1184.0,23095,,,,,,,...,[],,[],0,0,[],[],[],{},
109,ENSG00000116213,1053,1053.0,49856,49856,WRAP73,"WD repeat containing, antisense to TP73",9606,Homo sapiens,human,...,[WDR8],,"[{'assembly_accession': 'GCF_000001405.40', 'a...",9,9,"[{'type': 'PROTEIN_CODING', 'count': 1}, {'typ...","[{'id': '49856', 'method': 'NCBI Ortholog'}]",[{'description': 'This gene encodes a member o...,{'molecular_functions': [{'name': 'protein bin...,
63,ENSG00000160075,1042,1042.0,29101,29101,SSU72,"SSU72 homolog, RNA polymerase II CTD phosphatase",9606,Homo sapiens,human,...,"[HSPC182, PNAS-120]",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",1,1,"[{'type': 'PROTEIN_CODING', 'count': 1}]","[{'id': '29101', 'method': 'NCBI Ortholog'}]",[{'description': 'Enables RNA polymerase II CT...,{'molecular_functions': [{'name': 'MAP kinase ...,
183,ENSG00000171603,857,857.0,22883,22883,CLSTN1,calsyntenin 1,9606,Homo sapiens,human,...,"[CST-1, CSTN1, CDHR12, PIK3CD, ALC-ALPHA, XB31...",,"[{'assembly_accession': 'GCF_000001405.40', 'a...",5,5,"[{'type': 'PROTEIN_CODING', 'count': 3}, {'typ...","[{'id': '22883', 'method': 'NCBI Ortholog'}]",[{'description': 'This gene is a member of the...,{'molecular_functions': [{'name': 'X11-like pr...,
185,ENSG00000162441,659,659.0,84328,84328,LZIC,leucine zipper and CTNNBIP1 domain containing,9606,Homo sapiens,human,...,[],,"[{'assembly_accession': 'GCF_000001405.40', 'a...",11,11,"[{'type': 'PROTEIN_CODING', 'count': 5}, {'typ...","[{'id': '84328', 'method': 'NCBI Ortholog'}]",[{'description': 'Predicted to enable beta-cat...,{'molecular_functions': [{'name': 'beta-cateni...,
190,ENSG00000130939,631,631.0,10277,,,,,,,...,[],,[],0,0,[],[],[],{},
93,ENSG00000157916,622,622.0,11079,11079,RER1,retention in endoplasmic reticulum sorting rec...,9606,Homo sapiens,human,...,[],,"[{'assembly_accession': 'GCF_000001405.40', 'a...",1,1,"[{'type': 'PROTEIN_CODING', 'count': 1}]","[{'id': '11079', 'method': 'NCBI Ortholog'}]",[{'description': 'The protein encoded by this ...,{'molecular_functions': [{'name': 'acetylcholi...,